Add hexToAddress utility
enjin/php-blockchain-tools pull request #6
Opened 2022-07-25 19:33 UTC by Soletiq

2022-07-25 20:04 UTC, leonardocustodio reviewed
This is what we use on WAPI. The second one is also very interesting as sometime the other way around is needed.

```
    public static function formatAddress(string $address)
    {
        if (!str_starts_with($address, '0x')) {
            return $address;
        }

        return '0x' . substr($address, -40);
    }

    public static function formatAddressToEventTopic(string $address)
    {
        if (str_starts_with($address, '0x')) {
            $address = substr($address, 2);
        }

        return '0x' . str_pad(strtolower($address), 64, '0', STR_PAD_LEFT);
    }
```

2022-07-25 21:11 UTC, leonardocustodio approved these changes

2022-07-26 05:21 UTC, arttemiuss43 approved these changes

2022-07-26 05:33 UTC, arttemiuss43 requested changes
Should the documentation be updated accordingly?

2022-07-26 14:18 UTC, leonardocustodio approved these changes

2022-07-26 14:19 UTC, merged